### ISSUE TITLE
You primitives depend on Cython, but you do not define that dependency

### ISSUE THREAD

**Issue by mitar** [NewKnowledge/TimeSeries-D3M-Wrappers#10]
So [image building is failing](https://gitlab.com/datadrivendiscovery/images/-/jobs/359381937).

The problem is that `tslearn` requires it. To make this work, d3m primitives can define additional dependencies to install before their primitive itself is installed, in `installation` section.

It seems [you had that before, but it is not there anymore](https://gitlab.com/datadrivendiscovery/primitives/blob/master/archive/v2019.6.7/Distil/d3m.primitives.time_series_forecasting.arima.Parrot/1.0.3/primitive.json#L15-25).

I will disable your primitives for now.

**Comment by jlgleason** [comment]
Addressed in this commit: https://github.com/NewKnowledge/TimeSeries-D3M-Wrappers/commit/19f439c7f3816a7a7941dc5023c99ea0427ab392. PR will follow after validation succeeds

**Comment by rszeto** [comment]
The Cython version needs to be updated to 0.29.14 to avoid conflicting with the version specified by the object-detection-retinanet primitive.

Related links:
* [Pipeline failure (line 5015)](https://gitlab.com/datadrivendiscovery/primitives/-/jobs/386570067)
* [First mention of problem](https://gitlab.com/datadrivendiscovery/primitives/commit/5aeee65d01035f3c58e0c7b70dfcdbba5d713541#note_263968399)
* [Fix Cython issue on GitLab](https://gitlab.com/datadrivendiscovery/d3m/issues/418)

**Comment by mitar** [comment]
@jlgleason Could you bump Cython dependency to 0.29.14 and resubmit? Would that work for you?

**Comment by jlgleason** [comment]
Yes, that would work! We'll also fix the cython version in our object-detection-retinanet primitive to make sure those are always in step.
